### ISSUE TITLE
Check pinning of zarr

### ISSUE THREAD

**Issue by erikvansebille** [conda-forge/parcels-feedstock#105]
### Comment:

In #104, we pinned `zarr<2.18.0` because of Issue https://github.com/OceanParcels/parcels/issues/1564. Once the zarr package has been updated to 3.0, we should check if this pin can be removed

**Comment by ocefpaf** [comment]
Let's add the bot inspection here to update the recipe based on the metadata. Also, we need to do a repodata patch so the previous build number are also pinned. I can do not in later today.
