### ISSUE TITLE
Make sure that Parcels uses the linker installed by conda

### ISSUE THREAD

**Issue by willirath** [conda-forge/parcels-feedstock#15]
To achieve this, we probably only need to `export LDSHARED=${LD}`.

See https://github.com/conda-forge/pyferret-feedstock/blob/master/recipe/build.sh#L55_L62 and <https://github.com/conda-forge/pyferret-feedstock/tree/master/recipe/scripts> for how to do this.

**Comment by willirath** [comment]
> `export LDSHARED=${LD}`

Parcels uses `environ.get('LDSHARED', ld)` to override the linker: <https://github.com/OceanParcels/parcels/blob/d283b44fbb73fed0698a6625ba4d968f0f092c12/parcels/compiler.py#L37>

**Comment by VeckoTheGecko** [comment]
@erikvansebille  is this still current?

**Comment by erikvansebille** [comment]
No idea if it's still current. Perhaps @willirath knows?

**Comment by willirath** [comment]
Not sure. This issue came up on Mac, when the conda-provided `gcc` tried to use the (unavailable) system linker and raised an error, I think. I can dig up the Parcels issue and we can check this.

**Comment by willirath** [comment]
The related https://github.com/OceanParcels/Parcels/issues/332 has been fixed with https://github.com/OceanParcels/Parcels/pull/914. So we can close here.
