### ISSUE TITLE
Use Anaconda-5 gcc packages

### ISSUE THREAD

**Issue by willirath** [conda-forge/parcels-feedstock#3]
Per <https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html>, the `gcc` package should not be used any more.

We'll have to distinguish OSX and Linux dependencies here.

**Comment by isuruf** [comment]
You'll have to wait till conda-forge moves to conda-build=3 https://github.com/conda-forge/conda-smithy/pull/625

**Comment by willirath** [comment]
That's good to know.

Currently, the `gcc` dependency, which is satisfied from the defaults channel and `scipy`, which also comes from the defaults channel as there are a few broken packages for `conda-forge/scipy` interact in a way that `scipy.interpolate` triggers a lib error on import. Swapping `gcc` for `gcc_linux-64` seems to prevent this.

**Comment by willirath** [comment]
(We don't compile anything at build time, but need the compiler for just-in-time compilation at runtime.)

**Comment by jakirkham** [comment]
Maybe you could include a post-link script mentioning this requirement. Perhaps encouraging the user to set some environment variables that point at the right compiler. Even when we do have newer compiler packages, users may wish to bring their own compilers in.

**Comment by willirath** [comment]
That's a good point. This way, we'd probably be able to just have a noarch package with only minimal requirements here.

**Comment by willirath** [comment]
This is solved (for now) with d2c04f79aee4d9d11299ce02f7d68303fc34eaaf.
