### ISSUE TITLE
New version isn't published

### ISSUE THREAD

**Issue by willirath** [conda-forge/parcels-feedstock#45]
After #42 was merged, there was no package pushed to https://anaconda.org/conda-forge/parcels

@ocefpaf pushed an empty commit to no avail.

Bumping the build number with #43 didn't help.

What can we do next?

**Comment by ocefpaf** [comment]
I was going to suggest something like #47 and it seems that it worked, see https://anaconda.org/conda-forge/parcels/files?version=2.1.1. Sorry for the slow response @willirath and thanks for fixing this!
